### ISSUE TITLE
rush -e does not kill jobs

### ISSUE THREAD

**Issue by kubrat** [shenwei356/rush#17]
Example:
`seq 1 10 | rush -j 10 "sleep {} && exit 1" -e`

With `-e` rush will exit immediately as expected as soon as the first error is encountered but the rest of the jobs will keep running until completion which is a problem in my use case.

Note that this a Windows specific issue and the example uses the familiar `seq` and `sleep` which I have obtained through *MSYS2*.

**Comment by shenwei356** [comment]
Which version are you using?

**Comment by pwr22** [comment]
I think that `rush` should be doing a similar reaping of the child processes on windows in the case of a `-e` failure as it does like receiving a `ctrl+c`. What do you think @shenwei356 @kubrat?

If you agree I can work on this and put a PR together?

**Comment by shenwei356** [comment]
Totally agreed, PR is welcome!

**Comment by bburgin** [comment]
pwr22:

Thanks for your contribution. But can you put the new behavior behind a command line arg?
I have some workflows where I want the old -e behavior. For cases where I want to fail on the first error but not kill processes, so those processes can do clean up.

**Comment by pwr22** [comment]
@shenwei356 I've seen that `-e` doesn't work on linux either - seems to leave the old processes hanging around

@bburgin @shenwei356 putting this behind a different flag is fine with me. The current behaviour of `-e` is for `rush` to exit as soon as a child process fails but it leaves the others untouched. I'll call this `exit-early` for now

The behaviour I need is that as soon as any child process exits with failure that the entire batch is considered failed and terminated. I'll call this `fail-fast` for now

@bburgin I'd be interested to hear what workflows you have where you want to run a batch of stuff, have part of them fail, know that part failed but then have the rest of the batch running unmonitored in the background?

I'm not imaginitive enough 😆 to think of a scenario where running rush without `-e` wouldn't be better, since it leaves the other processes running but waits for them to complete and reports if any subsequent ones fail etc

**Comment by pwr22** [comment]
> For cases where I want to fail on the first error but not kill processes, so those processes can do clean up.

I'm not really familiar with Go's command execution stuff but doesn't it give processes a graceful signal and then some time to clean up before force killing? If it doesn't then that doesn't sound particularly well behaved...

**Comment by bburgin** [comment]
pwr22:

The go exec library does not correctly kill processes on Windows.
Thus, I added some code to rush to call taskkill on child processes, if you pass rush --kill-on-ctrl-c
	if isWindows {
		childProcess, err := psutil.NewProcess(int32(command.Process.Pid))
			if err != nil {
				Log.Error(err)
			}
			killWindowsProcessTreeRecursive(childProcess)
		} else {
			command.Process.Kill()
	}
The recursive method will kill leaf child processes first and proceed up the child process tree from there.

I would still like to have a different arg for the kill case. How about a --kill-on-error arg ?
This is so I can use the existing -e behavior (that doesn't kill), for cases like this:
1. Build tools that modify the file system
      The tools know how to clean themselves up on exit. But if they get killed, I don't know what files the tools touched or left in a bad state. I could run a general cleanup script at the start of every run of the tools, but this adds time to the build and I have to maintain a list of files /  folders to cleanup.    
2. Client apps that send operations to a server and then wait on them to be done
      If the clients get killed, the server will just continue executing the operations, using up server resources. If rush's -e could send a signit to child processes, that would help. The sigint could allow the client to signal the server to cancel its operation, freeing up server resources. But a kill would cause the server resources to be used until the operation completes.
3. Test tools that report results to a network server, but only at end of the test run
      I still want the results posted to the server, even on error.
4. A hardware test app that turns voltage output on and off, during a test sequence
      If the app gets killed, it could leave the voltage output on for an indeterminate amount of time. This would be a user hazard, if the voltage is high.

Like you said, if any of these operations is short enough, I could just use the normal rush behavior, without the -e. But some of the above operations take awhile and I would like to exit early if I can.
To help do this and still cleanup, you may want to look into a more graceful -e logic. You could make rush send sigint up the child process tree from leaf children, and then wait for the children to exit, without killing them. But I am unsure if the go signal library can send sigint to child processes on Windows.

If you want, you could also apply the sigint logic you make to --kill-on-ctrl-c and --kill-on-error.
Rush could send sigint, wait for some timeout time, and then call the kill recursive logic I mentioned above. But I would like an additional arg for the timeout, so the user can specify the timeout time to wait before killing. Here is an example of a wait loop:
https://stackoverflow.com/a/11886829

Thoughts?

**Comment by pwr22** [comment]
I'll play with `exec` and things a bit and see what I can come up with

**Comment by pwr22** [comment]
As far as I can tell the Windows signalling story is not good, especially for console applications. Outside of the equivalent of `SIGKILL` there doesn't really seem to be a standard signalling mechanism beyond `CTRL+C` keyboard events (and a few others but that'll be the best one to aim for)

So that's what I'll try to send from Go

**Comment by bburgin** [comment]
Sounds good. Maybe something like this code?:
https://github.com/mackerelio/mackerel-agent/blob/master/wix/wrapper/wrapper_windows.go

**Comment by pwr22** [comment]
> The go exec library does not correctly kill processes on Windows.

@bburgin could you clarify a bit more on this?

My guess based on the implementation of `killWindowsProcessTreeRecursive` is that killing something like `cmd.exe` didn't result in killing its children? If so then this is not a Go problem per se but a peculiarity of Windows

Not sure why there's any code to do killing on `ctrl+c` at all though - wouldn't it be better to just leave it to signal propagation to let children close up gracefully?

**Comment by pwr22** [comment]
> Sounds good. Maybe something like this code?:
https://github.com/mackerelio/mackerel-agent/blob/master/wix/wrapper/wrapper_windows.go

Looks quite similar to [this](https://github.com/golang/go/blob/master/src/os/signal/signal_windows_test.go#L19) I've found in the tests of Go itself 😆. I tested it and it seems to do the job 👍 

I've spent the last hour or so trying to find the appropriate place in the codebase to insert these changes but I think its a bit beyond me at this point 😕. Any chance someone more familiar with the codebase would like to take this up now that we have the "how"?

I guess the semantics I'd ideally like for `-e` would be for rush to detect the first failure, signal gracefully all the other processes (this `ctrl+c` is the best we can do on Windows but it should probably be `SIGTERM` on *NIX) and then exit itself. I don't really care too much about rush chasing up after misbehaving processes and I'd probably suggest that be behind some sort of `--force` type flag anyway

**Comment by pwr22** [comment]
> I am guessing that, yes, handling ctrl+c in rush means that no child process get ctrl+c unless rush explicitly sends it to the child processes. I have not tested this.

I tested `exec` in isolation and didn't see this behaviour 🤷‍♂️ 

> For who to implement the fix, I don't have the bandwidth to work on it. And it is more work than just adjusting the existing -e arg

That's fair enough. I took at look at how easy it would be to bolt it into the existing `-e` and given the flow of the program it'd be non-trivial for me to work out where to put it
