### ISSUE TITLE
Project name conflict

### ISSUE THREAD

**Issue by tseemann** [shenwei356/rush#20]
FYI - I went to add this to brewsci but found a conflict with this GNU project:

https://www.gnu.org/software/rush/

**Comment by shenwei356** [comment]
oh no, but I've used this in many places, can we just use another formula name in homebrew to avoid conflict?

**Comment by tseemann** [comment]
Yes you can give it a different name for the package eg. `rush-tool`.
But you won't be able to install `rush` and `rush-tool` at the same time.

Most common English words already exist as software tools I reckon :-)

**Comment by tueda** [comment]
I was wondering if there is a Homebrew formula for `rush` (or `rush-tool` etc), though it is straightforward to pick up the binaries on the Release page. I don't see it (at least) in the [homebrew-core](https://github.com/Homebrew/homebrew-core) or taps of [Brewsci](https://github.com/brewsci).
