### ISSUE TITLE
error "echo %TASKS% | rush zip -@ {}.zip < {}_input.txt"

### ISSUE THREAD

**Issue by jonnyyu** [shenwei356/rush#23]
I want to parallel running 2 zips with individual input file list on Windows:
I have debug_input.txt and release_input.txt in same directory

Here is how I write the code:

Set TASKS=debug release
echo %TASKS% | rush zip -@ {}.zip < {}_input.txt -D " " --dry-run

but it shows:
The system cannot find the file specified.

if I run 
echo %TASKS% | rush zip -@ {}.zip -D " " --dry-run
it shows 
unknown shorthand flag: '@' in -@

looks like I need escape for the '@', I tried

echo %TASKS% | rush zip -\@ {}.zip -D " " --dry-run
still
unknown shorthand flag: '\\' in -\@

how to write this rush command correctly?thx!

**Comment by shenwei356** [comment]
Set TASKS=debug release
    echo %TASKS% | rush 'zip -@ {}.zip < {}_input.txt ' -D " " --dry-run

**Comment by shenwei356** [comment]
I close this
