### ISSUE TITLE
Can't use non latin encoding in windows

### ISSUE THREAD

**Issue by bondspb** [shenwei356/rush#24]
Hi, nice tool, thx
I need local encoding but
echo Мир |rush "echo Привет " {}

output
������  ???

**Comment by shenwei356** [comment]
You can google with key words `windows 7/10 cmd utf8`. 

- https://superuser.com/questions/269818/change-default-code-page-of-windows-console-to-utf-8
- https://stackoverflow.com/questions/19955385/utf-8-in-windows-7-cmd

Excecuting `chcp 65001` works for me.
