### ISSUE TITLE
variables will not interpolated

### ISSUE THREAD

**Issue by jkroepke** [shenwei356/rush#25]
### Prerequisites

- [x] make sure you're are using the latest version by `rush -V`
- [x] read the usage (rush -h) and [examples](https://github.com/shenwei356/rush#examples)

### Describe your issue

* [x] describe the problem
Some Variable will not interpolated if the command contains some `{`. 

I need this because: https://stackoverflow.com/questions/24597818/exit-with-error-message-in-bash-oneline

* [x] provide a reproducible example

Expected result:
```
seq 1 3 | rush -k '{ echo "{} {A}" && echo "{} {A}"; }' -v A=4
1 4
1 4
2 4
2 4
3 4
3 4
```
Actual result:
```
seq 1 3 | rush -k '{ echo "{} {A}" && echo "{} {A}"; }' -v A=4
{} 4
1 4
{} 4
2 4
{} 4
3 4
```

Workaround (use a sub shell):
```
seq 1 3 | rush -k '( echo "{} {A}" && echo "{} {A}"; )' -v A=4
1 4
1 4
2 4
2 4
3 4
3 4
```

**Comment by shenwei356** [comment]
Hi, I think it's a design flaw of place holder.  For `rush -k '{ echo "{} {A}" && echo "{} {A}"; }'`, `rush` think `{ echo "{}` is a place holder.

We may use new format `{{}}`, `{{var}}`  to avoid this bug.

**Comment by shenwei356** [comment]
Well, I fixed this ... 

Please help test it:

- [rush_darwin_amd64.tar.gz](https://github.com/shenwei356/rush/files/2798975/rush_darwin_amd64.tar.gz)
- [rush_linux_amd64.tar.gz](https://github.com/shenwei356/rush/files/2798976/rush_linux_amd64.tar.gz)
- [rush_windows_amd64.exe.tar.gz](https://github.com/shenwei356/rush/files/2798977/rush_windows_amd64.exe.tar.gz)
