### ISSUE TITLE
{%.}, {%:}, basename without extension is just {/.} in GNU parallel

### ISSUE THREAD

**Issue by matrs** [shenwei356/rush#3]
Hey, your software looks great, i'll use it soon. 
I just notice in the Readme/Documentation It says this isn't supported in GNU parallel, which I think isn't true (except that parallel only removes periods by default):
```
Combinations (Combinations of 3+ replacement strings not supported in GNU parallel):
{%.}, {%:}, basename without extension
{2.}, {2/}, {2%.}, manipulate nth field
```
The first is achieved in GNU parallel simply using {/.}. You can also manipulate as many nth fields as you want:

```
$ VAR1=/house/inthe/tree/plays.to.mo.rrow
$ VAR2=/hey/hop/hip
$ VAR3=/up/down/left.right
$ parallel  --plus "echo {2/} {1/..} {3.}" ::: $VAR1 ::: $VAR2 ::: $VAR3
hip plays.to /up/down/left
```
(With plus I also removed two periods from field {1})

**Comment by shenwei356** [comment]
you're right. can you please help to submit a pull request, cause I can't have access to computer for 2 months.

**Comment by ole-tange** [comment]
It may be useful to look at this, too:
https://www.gnu.org/software/parallel/parallel_alternatives.html#DIFFERENCES-BETWEEN-Rush-AND-GNU-Parallel

**Comment by matrs** [comment]
@shenwei356 sure, i'll submit it during the week, you have any special requirement/direction to do it?

**Comment by shenwei356** [comment]
@matrs no any special requirement.
Thank @ole-tange , author of GNU parallel, for providing more comparison detail.
