### ISSUE TITLE
feature request: remote execution

### ISSUE THREAD

**Issue by mooreniemi** [shenwei356/rush#33]
### Prerequisites

- [x] make sure you're are using the latest version by `rush -V`
- [x] read the usage (rush -h) and [examples](https://github.com/shenwei356/rush#examples)

### Feature Request

Do you have any plans to support [Remote execution](https://www.gnu.org/software/parallel/parallel_tutorial.html#Remote-execution)?

**Comment by shenwei356** [comment]
Sorry, no.
