### ISSUE TITLE
Unable to extract files from tar

### ISSUE THREAD

**Issue by Teng-Zheng** [shenwei356/rush#34]
![image](https://user-images.githubusercontent.com/54031809/103846613-6d0fca80-5096-11eb-983d-4042424aca6f.png)

**Comment by shenwei356** [comment]
I've just downloaded and checked the file integrity, it's OK.

Please redownload.

```
$ md5sum  rush_linux_amd64.tar.gz 
4f6b552f1e4fa1adfe20bc1c85402172  rush_linux_amd64.tar.gz
```

**Comment by Teng-Zheng** [comment]
Thanks ! using go method i was successfully installed
