### ISSUE TITLE
escaping not working

### ISSUE THREAD

**Issue by ranjit-git** [shenwei356/rush#35]
it does not escape using -Q flag 
echo "http://localhost/?id=asdd=sdd&sdf=dff'&sdf=ff#df\`ds$gfg&sdf$sf"|rush -j 4 "{}"  -Q "'#" --dry-run --verbose
output=> http://localhost/?id=asdd=sdd&sdf=dff'&sdf=ff#df`ds&sdf   -->why its not escaping ' and #

**Comment by shenwei356** [comment]
forgot `-q`?

**Comment by ranjit-git** [comment]
I see -q is default but I want to escape more special character thus I want to use -Q

**Comment by ranjit-git** [comment]
ok got it , i need to use both -Q -q flags .
thanks
