### ISSUE TITLE
Please Update the new feature of progress bar

### ISSUE THREAD

**Issue by 0xhunster** [shenwei356/rush#37]
Hi there,
I hope you are doing well. Rush is a seriously very good script for parallel jobs/works. Many features in there. It would be great if there was a progress bar. It would be nice to see how many lines worked. This feature included an Interlace script. (https://github.com/codingo/Interlace) This feature really awesome. Do you have any plans to do that?

![15608](https://user-images.githubusercontent.com/46501627/120889772-822a5e80-c620-11eb-8e8c-40ac7c42f46e.png)

**Comment by shenwei356** [comment]
https://github.com/shenwei356/rush/pull/39

**Comment by shenwei356** [comment]
https://github.com/shenwei356/rush/releases/tag/v0.5.0

**Comment by 0xhunster** [comment]
Thanks for the update. but all result shows after the progress bar, which is very disturbing, Sometimes the results are broken and not understood. Please change that, So that all results show above the progress bar.

![image](https://user-images.githubusercontent.com/46501627/187120979-da8e3370-ddce-42ed-ad59-6bce21044eba.png)

**Comment by shenwei356** [comment]
The process bar is outputted to STDERR, which could be mixed with output from STDOUT. 

So you can either write results to a file:

    seq 10 | rush -j 1 'echo {}; sleep 1'  --eta > result.txt

Or redirect the progress bar to a log file.

    seq 10 | rush -j 1 'echo {}; sleep 1'  --eta 2> progress.txt

During the running, you can check progress.txt in another terminal.

    less progress.txt
