### ISSUE TITLE
How to understand which log belong to which input parameter?

### ISSUE THREAD

**Issue by mrtdem** [shenwei356/rush#38]
Hello there,

First of all thank you , rush is great problem solver tool.
We trying to implement rush for multi cluster deployment on kubernetes and other internal deployments in parallel.

I use rush with this pattern 
`echo -e "rollout status deployment/name-n xyznamespace\nrollout status deployment/name-n abcnamespace" | ./rush 'kubectl  {}'`
This pattern work without any problem with rush. But with 2 or 3 input, logs are getting complicated and we can't follow which logs belong which input.

For example
Can we add input parameter to beginning of the log like this
[1. parameter] status is waiting
[3. parameter] status is succeed
[2. parameter] status is failed

What can be done to fix this problem. Can we achieve with current version of rust?
If development is needed, i would be very happy to contribute

**Comment by bburgin** [comment]
Can you try the --immediate-output argument?

**Comment by mrtdem** [comment]
Thank you @bburgin . --immediate-output parameter solved my problem.
It's add [cmdID,tryNumber,lineNumber] before the output.

**Comment by shenwei356** [comment]
Thank you @bburgin !
