### ISSUE TITLE
{@regexp} Question

### ISSUE THREAD

**Issue by xtmgah** [shenwei356/rush#4]
What's is the {@regexp}, capture submatch using regular expression?  Do you have instruction about the regular expression recognized by rush? Thanks

**Comment by shenwei356** [comment]
read example 9 and changelog of v0.19 https://github.com/shenwei356/rush/releases/tag/v0.1.9

**Comment by xtmgah** [comment]
\d, \w, looks like it is similar to per regular expression? can i use other regular expression outside the example??

**Comment by shenwei356** [comment]
just try
