### ISSUE TITLE
Suggestion to improve documentation with practical examples.

### ISSUE THREAD

**Issue by teebu** [shenwei356/rush#40]
I just gotta say, this program is pretty cool, but hard to figure out. The documentation does not make it easy. Please include more practical examples, not just echos. Here's something I'm using it for:

Starting two (or more) azure cloudfunctions.
`run.sh`
```
#!/bin/bash
echo '
    cd operator_a && func start -p 7071; 
    cd service_worker_a && func start -p 7072
    ' \
    | rush --immediate-output -k -T b -D ';'   ' {} '
```

-D = delimiter (;)
-T = trim both sides of input (trying to have a neat script)
--immediate-output = only way to get output
-k = keep order (probably not important?)

**Comment by shenwei356** [comment]
I thought [18 examples](https://github.com/shenwei356/rush#examples) are sufficient. :smiling_face_with_tear:

Input can be given either from the STDIN (the echos) or files (`-i/--infile`); it should be flexible enough.

**Comment by teebu** [comment]
No that is way too cryptic. Everyone of those is very difficult to understand.

**Comment by shenwei356** [comment]
The help doc is updated.
