### ISSUE TITLE
Add a `go.mod` file

### ISSUE THREAD

**Issue by apcamargo** [shenwei356/rush#41]
I'm trying to push `rush` to Homebrew, but [they won't allow the creation of a `go.mod` file at build time](https://github.com/Homebrew/homebrew-core/pull/106770#pullrequestreview-1061342041). Would it be possible to have this file in the repository?

**Comment by shenwei356** [comment]
Sure, will do it tomorrow.

**Comment by apcamargo** [comment]
Thanks!

**Comment by shenwei356** [comment]
Added, and tagged a new release: https://github.com/shenwei356/rush/releases/tag/v0.4.3

**Comment by apcamargo** [comment]
Done https://github.com/Homebrew/homebrew-core/pull/106770

Thanks a lot for solving this quickly :)

**Comment by shenwei356** [comment]
thanks!
