### ISSUE TITLE
 Please update the go version in go.mod

### ISSUE THREAD

**Issue by yurivict** [shenwei356/rush#48]
### Prerequisites

- [x] make sure you're are using the latest version by `rush -V`
- [x] read the usage (rush -h) and [examples](https://github.com/shenwei356/rush#examples)

### Describe your issue

Please update the go version [here](https://github.com/shenwei356/rush/blob/master/go.mod#L3).

Some modules require higher go version, and the build of the FreeBSD port fails because go-1.17 is required.

**Comment by shenwei356** [comment]
Updated.
