### ISSUE TITLE
Update dependencies to remove CVE alerts

### ISSUE THREAD

**Issue by etilite** [shenwei356/rush#58]
Hello, can you please update imports?

## Problem
CVE scanners are triggered by this indirect dependency `golang.org/x/crypto v0.7.0` and it makes harder to use `rush` in some environments.

## Solution
By simply updating to `github.com/schollz/progressbar/v3 v3.10.0` we can remove this unnecessary import.

**Comment by shenwei356** [comment]
fixed.

- https://github.com/shenwei356/rush/pull/59
- https://github.com/shenwei356/rush/commit/36e68ceb6a83d0a39bfed5b120278c0e1d1bb033

**Comment by shenwei356** [comment]
new binaries: https://github.com/shenwei356/rush/releases/tag/v0.5.5

**Comment by etilite** [comment]
Thank you very much!
