### ISSUE TITLE
Problem passing string using curly brackets

### ISSUE THREAD

**Issue by hellishvictor** [shenwei356/rush#61]
Hi, here in Windows I need some help:
`coreutils echo "a attr{href}"="h4 text{}" | rush -k -D "=" echo {}` outputs:
```
a attr{href}
h4 texth4 text{}
```
when I want:
```
a attr{href}
h4 text{}
```
`text{}` has curly brackets with nothing inside, and since rush uses them also, it output wrong.
Is there a workaround for this?
Cheers.

**Comment by shenwei356** [comment]
fixed:
```
$ echo "a attr{href}"="h4 text{}" | rush -k -D "=" echo {}
a attr{href}
h4 text{}

$ echo -ne "a{},b{{}},c{d}" | rush -D , -k "echo {}" 
a{}
b{{}}
c{d}
```

[rush_windows_amd64.exe.tar.gz](https://github.com/user-attachments/files/17003824/rush_windows_amd64.exe.tar.gz)

**Comment by hellishvictor** [comment]
You're god, now it work like a charm! Thank you very much man!

**Comment by shenwei356** [comment]
@hellishvictor v0.5.7 introduced another bug if you use the option `-v` to set variables, which is fixed now and the feature you want is kept.

please update to the latest version: https://github.com/shenwei356/rush/releases/tag/v0.6.0

**Comment by hellishvictor** [comment]
Awesome, thank you very much!
