### ISSUE TITLE
Transitioning from GNU Parallel

### ISSUE THREAD

**Issue by abudavis** [shenwei356/rush#62]
Greetings from Scandinavia!
Version: rush v0.5.6
Platform: Kubernetes Pods/Linux x86-64

I couldn't find a suitable example for my use case: https://github.com/shenwei356/rush#examples
My use case is quite simple, I have a file called commands.txt as shown which will run for say git clone commands with different repos concurrently, for simplicity I have set the repo to be the same here.

I have been doing this so far using GNU Parallel where I fork some 200 threads for 200 lines of git clone. The actual command is not really git clone but something else.

What is the rush equivalent for accomplishing this? 
GNU Parallel command:
`parallel -j 200 < commands.txt`

commands.txt
```
git clone https://github.com/shenwei356/rush.git
git clone https://github.com/shenwei356/rush.git
git clone https://github.com/shenwei356/rush.git
git clone https://github.com/shenwei356/rush.git
git clone https://github.com/shenwei356/rush.git
git clone https://github.com/shenwei356/rush.git
git clone https://github.com/shenwei356/rush.git
git clone https://github.com/shenwei356/rush.git
git clone https://github.com/shenwei356/rush.git
git clone https://github.com/shenwei356/rush.git
```

**Comment by shenwei356** [comment]
cat commands.txt | rush -j 200 '{}'

or 

    rush -j 200 '{}' -i commands.txt
