### ISSUE TITLE
Fatal mistake: rush may break orders and cause line broken

### ISSUE THREAD

**Issue by bioinformatist** [shenwei356/rush#7]
When use rush to deal with SAM file, I find:
The `-k` parameter not works, also original-complete line may broken. To reproduce, you may run command below with attached files [example.tar.gz](https://github.com/shenwei356/rush/files/1404883/example.tar.gz):
```shell
head -n7 times | cut -f1 | rush "grep \"{}\" secondary_mapped.sam >> most.sam" -k
```
When parameter `--dry-run` is given, I get commands listed as below :
![image](https://user-images.githubusercontent.com/17194719/31861983-f5e0915c-b768-11e7-957f-b592f641e413.png)
See the order? **As same as** file `times` used in rush:
![image](https://user-images.githubusercontent.com/17194719/31861993-1c2ffe06-b769-11e7-8266-030b0389b488.png)
But **the order comes wrong**

 when I remove `--dry-run`:
![image](https://user-images.githubusercontent.com/17194719/31862008-62cd09e4-b769-11e7-93e4-c4f728a1aafd.png)
Also, lines may be **broken** by rush:
![image](https://user-images.githubusercontent.com/17194719/31861941-3ffe6a94-b768-11e7-99fd-f598b64fbc6d.png)

But when I use only one thread (`-j 1`) at a time, everything is OK.
```shell
head -n7 times | cut -f1 | rush "grep \"{}\" secondary_mapped.sam >> most.sam" -k -j1
```

**Comment by shenwei356** [comment]
Well, It's not a bug of `rush`.

You should not simultaneously append data to one file.

The right command:

```
head -n7 times | cut -f1 | rush "grep \"{}\" secondary_mapped.sam" -k >  most.sam
```

**Comment by likelet** [comment]
wtf
